name: detours prebuilt
on: workflow_dispatch
env:
  # Turn on msvc analysis during build, enable once warnings are clean.
  DETOURS_ANALYZE: true

  # Compile in parallel where possible.
  CL: /MP

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        arch: [x86, x64, arm, arm64]
        build_type: [Release]

        include:
          - arch: x86
            msvc: x86
          - arch: x64
            msvc: x64
          - arch: arm
            msvc: x64_arm
          - arch: arm64
            msvc: x64_arm64

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Configure MSCV Compiler for ${{ matrix.arch }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc }}

      - name: Build Detours for ${{ matrix.arch }} on ${{ matrix.os }} 
        env:
          DETOURS_TARGET_PROCESSOR: ${{ env.VSCMD_ARG_TGT_ARCH }}
          DETOURS_CONFIG: ${{ matrix.build_type }}
        run: nmake

      - name: Upload artifacts for ${{ matrix.arch }} on ${{ matrix.os }} 
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            lib.*/
            bin.*/
            include/
