name: detours prebuilt
on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        arch: [x86, x64, arm, arm64]
        build_type: [Release]
        version: [4.0.1]

        include:
          - os: windows
            runner: windows-2019
          - arch: x86
            msvc: x86
          - arch: x64
            msvc: x64
          - arch: arm
            msvc: x64_arm
          - arch: arm64
            msvc: x64_arm64

    steps:
      - name: Clone Detours
        uses: actions/checkout@v2
        with:
          path: detours

      - name: Configure MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc }}

      - name: Build Detours
        env:
          DETOURS_TARGET_PROCESSOR: ${{ env.VSCMD_ARG_TGT_ARCH }}
          DETOURS_CONFIG: ${{ matrix.build_type }}
        working-directory: detours/src
        run: nmake

      - name: Package Detours
        shell: pwsh
        working-directory: detours
        run: |
          $PkgDir = "detours-${{matrix.version}}-${{matrix.arch}}"
          New-Item -ItemType Directory -Path $PkgDir | Out-Null
          Move-Item "./include" -Destination $PkgDir -Recurse
          Move-Item "./lib.*" -Destination $PkgDir -Recurse
          Get-ChildItem $PkgDir -Recurse
